Feature newsweek
Ahmed-Benj/Newsweek-Clone pull request #1
Opened 2020-10-01 23:11 UTC by Ahmed-Benj

Hello TSE,

Could you please review our work on this project ?

Kind regards,
Ahmed

2020-10-03 00:18 UTC, teekaytech requested changes
## Status: Changes Required :warning: :construction:

### Hi team :wave: 
So far, this is great work: the progress is promising and I believe that after a couple of changes, the project should be ready. Talking about changes, let us review some of the changes required (see comments below).

**[ REQUIRED CHANGES ]** 

- [x] Although you have a brief description, it does not really summarize what the PR all about. Kindly update your PR description. [This guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) might help in preparing a professional pull request description. 

Source page:
![00:26:26](https://user-images.githubusercontent.com/26856491/94977076-1c288d00-050f-11eb-814e-639ebc2de986.png)

Your clone:
![00:25:49](https://user-images.githubusercontent.com/26856491/94977078-1df25080-050f-11eb-94f5-0eaa81146464.png)


- [x] The date section is missing on your page. Please add it.

![00:27:11](https://user-images.githubusercontent.com/26856491/94977107-3a8e8880-050f-11eb-9558-79734e2f3f81.png)

- [x] Your footer should contain the Newsweek logo. Kindly add it.

Source page:
![00:38:07](https://user-images.githubusercontent.com/26856491/94977491-d8368780-0510-11eb-85ef-ecf015424b4c.png)

Your clone page:
![00:38:29](https://user-images.githubusercontent.com/26856491/94977495-de2c6880-0510-11eb-8bb4-688596f0ff6f.png)

- [x] Since the main point of this project is to use bootstrap for your layout, you are not expected to use `display: flex` or `display: grid` rules in your CSS file. 
- There are bootstrap classes for these rules, please use them. Here is bootstrap references for [flex](https://getbootstrap.com/docs/4.3/utilities/flex/) and [grid](https://getbootstrap.com/docs/4.3/layout/grid/) layouts

![00:42:20](https://user-images.githubusercontent.com/26856491/94977589-5b57dd80-0511-11eb-91bc-80c56a7a0d66.png)

- [x] Your footer seems to be missing the pipe symbols `|` separating each item. Please add them all.

Source page:
![01:13:59](https://user-images.githubusercontent.com/26856491/94978561-cacfcc00-0515-11eb-99bf-7f6f2eb6b894.png)

Your page:
![01:14:20](https://user-images.githubusercontent.com/26856491/94978565-ce635300-0515-11eb-8ebe-bed92e20c873.png)


**At 1024px screen size:**

- [x] There seems to be some overlap/overflow in your navbar. Kindly review and fix it.

Source page:
![00:53:45](https://user-images.githubusercontent.com/26856491/94977931-fac9a000-0512-11eb-8083-916ca1d07022.png)

Your page:
![00:53:33](https://user-images.githubusercontent.com/26856491/94977937-00bf8100-0513-11eb-9a9f-ce3003bf8e1e.png)

- [ ] `The Debate` section changes its layout. Please fix it

| Source Page | Your Clone Page |
| ----------- | ----------- |
| ![00:58:07](https://user-images.githubusercontent.com/26856491/94978060-880cf480-0513-11eb-8c6e-b78b259affc7.png) | ![00:57:58](https://user-images.githubusercontent.com/26856491/94978073-93602000-0513-11eb-830c-c4c48262abbf.png) |

- [x] Compare your entire page with the source page and take care of the following:
- Font boldness, paddings, and margins
- Image responsiveness
- White spaces between each section (e.g. space between `In the magazine` and `Editors' Picks` section.

- [ ] Please check the comments I made in the code section below and do the needful.

**[ OPTIONAL CHANGES ]**

- [ ] You are advised to use semantic HTML always. Semantic HTML5 tags like `<header>`, <main>`, `<article>`, <section>` etc should be used as appropriate in your project.

- [ ] Linter files are present in your project, but they are not executed by GitHub Actions. Since you already set them up, you should find a way to make the checks run on your PR.

**[ COMMENTS ]**

- [ ] I observed that in a couple of places in your style.css file, you used the `!important` rule often. Although this might get the work done, you should be careful not to overuse the rule as it might mess things up for you in the future.

- [ ] Also, I observed that in your index.html file, you used a lot of SVG images directly. I'm not against using SVG images, but personally, I think it's better to have them stored in your assets folder, then you reference them in your HTML file just like images. This makes your code cleaner and readable.

* **When you have made the specified changes, please submit another code review. Thank you!**
* **If you feel like you need help or you have any question(s), I'm @taofeekolalere on slack**

Regards,
[Taofeek Olalere](https://github.com/teekaytech) (@taofeekolalere on slack)
Happy Coding :technologist:

2020-10-03 00:18 UTC, teekaytech commented on README.md
> +
Please add your live demo link. [this resource](https://raw.githack.com/) might help.

2020-10-03 00:18 UTC, teekaytech commented on assets/css/style.css
> +
Since you comment on these blocks of code, it is a good practice to remove them completely. 

![23:59:01](https://user-images.githubusercontent.com/26856491/94975965-44ae8800-050b-11eb-8a81-da6a9ab6a68b.png)

2020-10-03 00:18 UTC, teekaytech commented on index.html
> +                  />
The `alt` attribute is missing in this `<img>` tag. This is a recurring issue in this file. Kindly add it here and all other places where it might be missing.

2020-10-03 00:18 UTC, teekaytech commented on assets/css/style.css
> +  display: flex;
This is a bootstrap project. You should use bootstrap [flex utility classes](https://getbootstrap.com/docs/4.3/utilities/flex/). Kindly fix this and other occurrences of such.

2020-10-04 18:28 UTC, Ahmed-Benj commented on README.md
> +
Done with netlify

2020-10-15 21:00 UTC, Ahmed-Benj commented on assets/css/style.css
> +
Done

2020-10-15 21:01 UTC, Ahmed-Benj commented on assets/css/style.css
> +  display: flex;
removed all unnecessary occurences of flex in css and replaced them by bootstrap classes d-flex

2020-10-15 21:51 UTC, Ahmed-Benj commented
Hello Sir,

I have fixed all requested changes, could you pleease approve my project ?

Kind regards,
Ahmed

2020-10-15 21:52 UTC, Ahmed-Benj commented
Fixed all of them

2020-10-15 21:52 UTC, Ahmed-Benj commented on index.html
> +                  />
Fixed all the items

2020-10-15 23:29 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing fixing those required changes in the last review. However, this project is still not complete, therefore I cannot approve it. Let's quickly fix the changes identified and re-submit another review request.__

**[ REQUIRED CHANGES ]**

_Do not be discouraged. This is a big project and most times, some changes may lead to another. Also, we need to ensure that nothing is messed up with the page layout across different breakpoints._

- [ ] Since the main point of this project is to use Bootstrap, kindly use more bootstrap classes for features like padding, margin, width, color, etc. You're using more CSS rules than bootstrap classes. Try to study bootstrap more so that you can fully utilize its classes.

- [ ] Your live demo link still presents the old version of the project. Kindly ensure that your changes are being tracked by Netlify so that it renders your updated project. As an option, you can use [githack](http://rawcdn.githack.com/).

- [ ] Your linter checks are not running. You should ensure that GitHub Actions checks your linters and no error is returned.

- [x] Your navbar items are not well-spaced. Kindly fix it.

Original page:
![23-52-13](https://user-images.githubusercontent.com/26856491/96194064-78dd6c00-0f41-11eb-8227-e20ea4844d5c.png)

Your page:
![23-51-48](https://user-images.githubusercontent.com/26856491/96194072-7c70f300-0f41-11eb-9e02-75ef527ac322.png)

- [x] You have some missing components/sections and layout issues.
- Your content is too condensed without space. Please check the image below for a better understanding
- `The Debate` section is missing on your page. Kindly re-add it.
- Ensure that each article's title is well distinguished from the summary. Use a bigger font size and bold to make it similar to the original page.

Original Page:
![23-59-58](https://user-images.githubusercontent.com/26856491/96194575-8d6e3400-0f42-11eb-9ca1-85e99ec41cd9.png)

Your Page:
![00-02-42](https://user-images.githubusercontent.com/26856491/96194739-f2298e80-0f42-11eb-8f0e-9327955ff334.png)

- [ ] Add a little space between the `In the Magazine` and `Editor's Pick` section.

- [ ] The `My Turn` and `Culture & Travel` section is missing. Please add those sections.

- [ ] The red Newsweek logo is missing in your footer. Kindly add it.

**At medium screen sizes**

- [ ] The date on the top navbar should be hidden.

**At small screen sizes** <768px

- [ ] Try to check the original page and make sure that the contents of your page look similar to what we have there. See the images below for some instances.

| Original Page | Your clone page |
| --------------- | ------------------- |
| ![00-17-42](https://user-images.githubusercontent.com/26856491/96195591-0a021200-0f45-11eb-8c4a-cabbce30442e.png) | ![00-17-12](https://user-images.githubusercontent.com/26856491/96195607-17b79780-0f45-11eb-82a9-8bc05134510e.png) |
| ![00-19-09](https://user-images.githubusercontent.com/26856491/96195738-6fee9980-0f45-11eb-9f66-e6278a694d11.png) | ![00-20-20](https://user-images.githubusercontent.com/26856491/96195749-77ae3e00-0f45-11eb-84a0-1912948dfef1.png) |


**[ COMMENTS ]**
- Please take some time to carefully compare your page with the original page. Then, make sure that your page looks similar to the source page.
- In this project, you have to be more precise. Apply all texts and images formatting as seen on the original page. 


**Please make the required changes and submit another review request when you are done.**


* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-24 00:10 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @Ahmed-Benj and @Ramon-Carrillo  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes in the previous reviews, keep it up, and your project really has a great progress.
## :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# Required Changes
- [ ] Sorry for that it was not mentioned earlier baut your clone has some extra-space on each side, which is different than the original page
Your clone:
![Screenshot from 2020-10-24 01-57-23](https://user-images.githubusercontent.com/56886064/97062673-47e1e480-159c-11eb-8e5e-ccf7ffe9bac3.png)

Original page: 
![Screenshot from 2020-10-24 01-57-56](https://user-images.githubusercontent.com/56886064/97062696-5e883b80-159c-11eb-8df1-9a4a18705b28.png)
- [ ] In the navbar, there should be some dummy weather data above of datetime section
Your clone : 
![Screenshot from 2020-10-24 01-59-35](https://user-images.githubusercontent.com/56886064/97062749-97281500-159c-11eb-87f3-1f313f1fc0b3.png)
Original page: 
![Screenshot from 2020-10-24 02-00-09](https://user-images.githubusercontent.com/56886064/97062773-ac04a880-159c-11eb-836c-8f2010a0c6c0.png)
- [ ] In options bar, the search input should be input type text, it's not a link
- [ ] Instead of using US as a title use US, business, world, culture, tech & science, sports
- [ ] Make sure that your linters are run on github actions
- [ ] Fix all the comments I added directly in your codes

# Optional changes
- [ ] Your commit messages should be in imperative mode, something like modify to solve linters reviews in css code instead of modified to solve linters reviews in css code, refer [to this article for mor details](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-10-24 00:10 UTC, descholar-ceo commented on index.html
> +      rel="stylesheet"
Please remove this commented codes

2020-10-27 01:12 UTC, Ahmed-Benj commented on index.html
> +      rel="stylesheet"
Done

2020-10-27 02:01 UTC, jubaan approved these changes
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. All changes required by previous TSE are done.

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

2020-10-27 06:29 UTC, merged